name: Run schema validation
on:
  pull_request:
  workflow_dispatch:

# if this branch is pushed back to back, cancel the older branch's workflow
concurrency:
  group: ${{ github.ref }} && ${{ github.workflow }}
  cancel-in-progress: true

# needed for Commit and push OpenAPI changes to work
permissions:
  contents: write

jobs:
  schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # needed for Commit and push OpenAPI changes to work
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - uses: actions/setup-node@v4
      - name: Read Node version from .nvmrc
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      # This workflow exists so we do not have to locally generate the OpenAPI spec.
      # If the OpenAPI spec has changed, it commits and pushes those changes back to the PR branch
      - name: Generate OpenAPI docs from code
        run: npm run generate:openapi

      - name: Check if OpenAPI docs have changed
        id: check_changes
        run: |
          if git diff --quiet src/api-docs/openapi.yml src/api-docs/openapi.json; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push OpenAPI changes
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update OpenAPI spec'
          add: 'src/api-docs/openapi.yml src/api-docs/openapi.json'
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create empty commit to re-run checks
        if: env.changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --allow-empty -m "Re-run checks after OpenAPI update"
          git push origin HEAD:${{ github.head_ref }}

      - name: Fetch main branch for Optic
        run: git fetch --depth=1 origin main:main

      - name: Optic diff
        run: npm run optic:diff
